use_gpu: True
verbose: False

# path to the label file, relative to the src/cae/ path.

label_path: outputs/normalized_mapping.pickle
# mask_path: /mnt/nfs/work1/mfiterau/zguan/clinica_data/mask_ICV.nii
# image_col: [ gray_matter_path ]
# image_col: [ gray_matter_path, white_matter_path, csf_path ]
image_col: [ misc ]
label_col: label

data:
    set_name: presliced
    # 2D vs 3D
    num_dim: 2
    slice_view: coronal
    # can specify one or three slice indices
    # If one slice index is specified and one image_col is specified, the resulting slice is repeated and stacked so there are 3 channels.
    # Otherwise either three image-cols, or three slice_nums can be specified, leading to a three channel image.
    slice_num: [ 80 ]
    max_workers: 0
    valid_split: 0.1
    test_split: 0.1
    limit: 20
    transforms:
        resize: 224
        range_norm: True
        mean_std_norm: False

model:
    class: resnet18
    # for pretrained models only
    pretrained: True
    # number of residual blocks per group
    num_blocks: [1, 1, 1, 1, 1]

pretrain:
    optim:
        name: adam
        learn_rate: 0.0001
        weight_decay: 0.00001
        momentum: 0.9
    num_epochs: 0
    batch_size: 4
    print_iter: 4
    sparsity: 0.0003

train:
    optim:
        name: sgd
        learn_rate: 0.001
        weight_decay: 0.001
        momentum: 0.9
    num_epochs: 20
    batch_size: 16
    print_iter: 1
    save_model: True
    # freeze the weights of the CNN layers
    freeze_cnn: False
    cnn_dropout: 0.0
    class_dropout: 0.0

valid:
    batch_size: 16

test:
    batch_size: 16


remarks: 2D classification
