use_gpu: True
verbose: False

# path to the label file, relative to the src/cae/ path.

# label_path: outputs/files_manifest.pickle
# image_col: postproc_path
# label_col: label

# label_path: outputs/surfer_labels.pckl
# image_col: PROC_IMGPATH
# label_col: DX

label_path: outputs/normalized_mapping.pickle
# image_col: [ gray_matter_path ]
image_col: [ gray_matter_path, white_matter_path, csf_path ]
label_col: label

data:
    set_name: normalized
    max_workers: 6
    valid_split: 0.2
    test_split: 0.1
    limit: -1

model:
    class: deep_ae_mri
    # number of residual blocks per group
    num_blocks: [1, 1, 1, 1, 1]

pretrain:
    num_epochs: 200
    batch_size: 6

train:
    optim:
        learn_rate: 0.01
        weight_decay: 0.0001
        momentum: 0.9
    num_epochs: 40
    batch_size: 20
    print_iter: 5
    save_model: True
    freeze_cnn: True

valid:
    batch_size: 20

test:
    batch_size: 20


remarks: 21-layers without gloabl average pooling and uses SGD
