use_gpu: True
verbose: False

# path to the label file, relative to the src/cae/ path.

# label_path: outputs/files_manifest.pickle
# image_col: postproc_path
# label_col: label

label_path: outputs/surfer_labels.pckl
image_col: [ PROC_IMGPATH ]
label_col: DX

label_path: outputs/normalized_mapping.pickle
mask_path: /mnt/nfs/work1/mfiterau/zguan/clinica_data/mask_ICV.nii
# image_col: [ gray_matter_path ]
# image_col: [ gray_matter_path, white_matter_path, csf_path ]
image_col: [ misc ]
label_col: label

data:
    # clinica
    # set_name: normalized
    # free surfer
    set_name: classify
    # 2D vs 3D
    num_dim: 3
    slice_view: coronal
    # can specify one or three slice indices
    # If one slice index is specified and one image_col is specified, the resulting slice is repeated and stacked so there are 3 channels.
    # Otherwise either three image-cols, or three slice_nums can be specified, leading to a three channel image.
    slice_num: [ 78, 88, 98 ]
    max_workers: 4
    valid_split: 0.2
    test_split: 0.2
    limit: -1
    transforms:
        pad_to_same: True
        nan_to_num: 0
        range_norm: True

model:
    class: deep_ae_mri
    # class: hosseini_three_layer
    # number of residual blocks per group
    num_blocks: [1, 1, 1, 0, 0]

pretrain:
    optim:
        name: adam
        learn_rate: 0.001
        weight_decay: 0.0001
        momentum: 0.9
    num_epochs: 0
    batch_size: 2
    print_iter: 1
    sparsity: 0.0003

train:
    optim:
        name: adam
        learn_rate: 0.001
        weight_decay: 0.0001
        momentum: 0.9
        use_scheduler: False
        # decay every n epochs
        step_size: 10
        # multiplicative factor applied to learning rate
        decay_factor: 0.5
    num_epochs: 100
    batch_size: 4
    print_iter: 1
    save_model: True
    freeze_cnn: False
    cnn_dropout: 0.0
    class_dropout: 0.0

valid:
    batch_size: 4


test:
    batch_size: 4



remarks: Classification of skull-stripped images
