use_gpu: True
verbose: False

# path to the label file, relative to the src/cae/ path.

# label_path: outputs/files_manifest.pickle
# image_col: postproc_path
# label_col: label

# label_path: outputs/surfer_labels.pckl
# image_col: PROC_IMGPATH
# label_col: DX

label_path: outputs/normalized_mapping_subset.pickle
image_col: gray_matter_path
label_col: label

data:
    set_name: normalized
    max_workers: 1
    valid_split: 0.1
    test_split: 0.1
    limit: -1

model:
    class: deep_mri

pretrain:
    num_epochs: 0
    batch_size: 10

train:
    num_epochs: 200
    optim:
        learn_rate: 0.001
        weight_decay: 0.00001
    batch_size: 10
    print_iter: 5
    save_model: True

valid:
    batch_size: 10

test:
    batch_size: 10


remarks: Using deep MRI with gray matter images.
