use_gpu: True
task: classify
# path to the label file, relative to the src/cae/ path.
# label_path: outputs/files_manifest.pickle
# image_col: postproc_path
# label_col: label
label_path: outputs/surfer_labels.pckl
image_col: PROC_IMGPATH
label_col: DX

data:
    set_name: classify
    max_workers: 4
    valid_split: 0.2
    test_split: 0.2
    limit: -1

model:
    class: hosseini_deep

pretrain:
    num_epochs: 0

train:
    num_epochs: 100
    optim:
        learn_rate: 0.01
        weight_decay: 0.1
    batch_size: 4
    print_iter: 1
    save_model: True

valid:
    batch_size: 4

test:
    batch_size: 4

remarks: Experiment with pixel values normalized to between -1 and 1 and updated mapping file.
