use_gpu: True
task: classify
# path to the label file, relative to the src/cae/ path.
# label_path: outputs/files_manifest.pickle
# image_col: postproc_path
# label_col: label
label_path: outputs/surfer_labels.pckl
image_col: PROC_IMGPATH
label_col: DX

data:
    set_name: classify
    max_workers: 2
    valid_split: 0.2
    test_split: 0.2
    limit: -1

model:
    class: deep_mri

pretrain:
    num_epochs: 0

train:
    num_epochs: 100
    optim:
        learn_rate: 0.01
        weight_decay: 0.1
    batch_size: 2
    print_iter: 5
    save_model: True

valid:
    batch_size: 2

test:
    batch_size: 2

remarks: Using 24-layer network.
