use_gpu: True
task: classify

data:
    set_name: classify
    max_workers: 6
    valid_split: 0.2
    test_split: 0.2
    limit: -1

model:
    class: hosseini

pretrain:
    skip: False
    num_epochs: 100

train:
    num_epochs: 200
    optim:
        learn_rate: 0.1
        weight_decay: 0.0
    batch_size: 4
    print_iter: 1
    save_model: True

valid:
    batch_size: 4

test:
    batch_size: 4

remarks: Running on the entire set.
