use_gpu: True
task: classify

data:
    set_name: classify
    max_workers: 6
    valid_split: 0.2
    test_split: 0.2
    limit: 20

model:
    class: hosseini_three_layer

pretrain:
    skip: False
    num_epochs: 1

train:
    num_epochs: 1
    optim:
        learn_rate: 0.1
        weight_decay: 0.0
    batch_size: 2
    print_iter: 1
    save_model: True

valid:
    batch_size: 2

test:
    batch_size: 2

remarks: Full run with the set.
