use_gpu: True
task: classify

data:
    set_name: classify
    max_workers: 4
    valid_split: 0.2
    test_split: 0.2
    limit: -1

model:
    class: hosseini_deep

pretrain:
    num_epochs: 0

train:
    num_epochs: 100
    optim:
        learn_rate: 0.01
        weight_decay: 0.2
    batch_size: 2
    print_iter: 5
    save_model: True

valid:
    batch_size: 2

test:
    batch_size: 2

remarks: Run with full dataset, 12-layer network with residual connection.
