use_gpu: True

data:
    set_name: classify
    max_workers: 0
    valid_split: 0.1
    test_split: 0.1
    limit: 10

model:
    class: hosseini

pretrain:
    skip: False
    num_epochs: 10

train:
    num_epochs: 24
    optim:
        learn_rate: 0.1
        weight_decay: 0.0
    batch_size: 2
    print_iter: 10
    save_model: True

valid:
    batch_size: 2

test:
    batch_size: 2

remarks: Run on small set to see if model overfits.
