use_gpu: True

data:
    set_name: classify
    max_workers: 10
    valid_split: 0.2

model:
    class: classify

train:
    num_epochs: 24
    optim:
        learn_rate: 0.1
        weight_decay: 0.0
    batch_size: 8
    print_iter: 2
    save_model: True

valid:
    batch_size: 8

remarks: Run on small set to see if model overfits.
