use_gpu: True

data:
    set_name: classify
    max_workers: 1
    valid_split: 0.2
    limit: 512

model:
    class: classify

train:
    num_epochs: 24
    optim:
        learn_rate: 0.1
        weight_decay: 0.0
    batch_size: 1
    print_iter: 10
    save_model: True

valid:
    batch_size: 1

remarks: Run on small set to see if model overfits.
